import enUS from './en-US';

const ar = {
    ...enUS,
    about: 'حول البرنامج', addItem: 'إضافة عنصر', applyChanges: 'تطبيق التغييرات', applyChangesConfirm: 'هل تريد تطبيق التغييرات المعلّقة؟', applyChangesFailed: 'تعذر تطبيق التغييرات.', applyChangesSucceeded: 'تم تطبيق التغييرات.', applyWarnings: 'تحذيرات',
    available: 'متاح', availabilityStatus: 'حالة التوفر', browse: 'استعراض', browseFile: 'ملف', browseFolder: 'مجلد', cancel: 'إلغاء', close: 'إغلاق', contentConnected: 'المحتوى المشفّر متصل', contentOperations: 'عمليات المحتوى', continueAction: 'متابعة', copyrightNotice: 'إشعار حقوق النشر',
    createProject: 'إنشاء مشروع', createProjectConfirm: 'هل تريد إنشاء المشروع وبدء تشفير المجلد المصدر المحدد؟', createProjectFailed: 'تعذر إنشاء المشروع.', createProjectSucceeded: 'تم إنشاء المشروع.', createShare: 'إنشاء مشاركة', createShareFailed: 'تعذر إنشاء المشاركة.', createShareSucceeded: 'تم إنشاء المشاركة.', createSourcePath: 'مسار المجلد المصدر', dataDirectory: 'دليل البيانات',
    decryptProject: 'فك تشفير المشروع', decryptProjectFailed: 'تعذر فك تشفير المشروع.', decryptProjectSucceeded: 'تم فك تشفير المشروع.', decryptShare: 'فك تشفير المشاركة', decryptShareFailed: 'تعذر فك تشفير المشاركة.', decryptShareSucceeded: 'تم فك تشفير المشاركة.', defaultMaxPartSize: 'الحد الأقصى الافتراضي لحجم الجزء (ميغابايت)',
    deleteProject: 'حذف المشروع', deleteProjectConfirm: 'هل تريد حذف قاعدة بيانات المشروع المحلية من دليل FG؟', deleteProjectFailed: 'تعذر حذف المشروع.', deleteProjectSucceeded: 'تم حذف المشروع.', discard: 'تجاهل', discardChanges: 'تجاهل التغييرات', encryptedContentPath: 'مسار المحتوى المشفّر',
    errorLoadingProjects: 'تعذر تحميل المشاريع المحلية.', errorLoadingSettings: 'تعذر تحميل الإعدادات.', errorOperationFailed: 'فشلت العملية. تحقق من الإدخال وحاول مرة أخرى.', errorOutputFolderNotEmpty: 'مجلد الإخراج غير فارغ. أفرغه أو فعّل الاستبدال الإجباري.', errorPasswordIncorrect: 'كلمة المرور غير صحيحة أو لا يمكن فتح قاعدة البيانات بها.', errorSavingSettings: 'تعذر حفظ الإعدادات.',
    errorInsufficientDiskSpace: 'لا توجد مساحة خالية كافية على قرص الإخراج لإكمال العملية.', errorIncrementalRequiresSplit: 'يتطلب الحذف حسب الجزء حجماً أقصى محدوداً للجزء. اضبط تقسيم الملفات.', exportProject: 'تصدير المشروع', exportProjectFailed: 'تعذر تصدير المشروع.', exportProjectSucceeded: 'تم تصدير المشروع.',
    fileCount: 'عدد الملفات', fileSize: 'حجم الملف', foldersGuard: 'FoldersGuard', folderName: 'اسم المجلد', folderCount: 'عدد المجلدات', formatVersion: 'إصدار التنسيق', home: 'الرئيسية', importProject: 'استيراد المشروع', importProjectFailed: 'تعذر استيراد المشروع.', importProjectSucceeded: 'تم استيراد المشروع.', inspectProject: 'فحص المشروع', inspectShare: 'فحص المشاركة', invalidItemName: 'أدخل اسماً واحداً صالحاً بلا فواصل مسار.', itemDetails: 'تفاصيل العنصر', itemName: 'الاسم', itemPath: 'المسار', itemType: 'النوع', itemTypeFile: 'ملف', itemTypeFolder: 'مجلد',
    verifyProject: 'التحقق من محتوى المشروع', verifyProjectFailed: 'تعذر التحقق من المشروع.', verifyProjectSucceeded: 'تم التحقق من محتوى المشروع.', verifyShare: 'التحقق من محتوى المشاركة', verifyShareFailed: 'تعذر التحقق من المشاركة.', verifyShareSucceeded: 'تم التحقق من محتوى المشاركة.', language: 'اللغة', languageEnglishUS: 'الإنجليزية (الولايات المتحدة)', languageSimplifiedChinese: 'الصينية المبسطة', languageArabic: 'العربية', languageFrench: 'الفرنسية', languageRussian: 'الروسية', languageSpanish: 'الإسبانية', languageSystem: 'النظام', loading: 'جارٍ التحميل',
    localProjects: 'المشاريع المحلية', noProjects: 'لم يتم العثور على مشاريع محلية.', noPendingChanges: 'لا توجد تغييرات معلّقة.', password: 'كلمة المرور', passwordConfirm: 'تأكيد كلمة المرور', passwordMismatch: 'كلمتا المرور غير متطابقتين.', pendingChanges: 'التغييرات المعلّقة', projectName: 'اسم المشروع', refresh: 'تحديث', removeItem: 'حذف العنصر', renameItem: 'إعادة تسمية العنصر', saveSettings: 'حفظ الإعدادات', searchProjects: 'البحث في المشاريع', selectedShareItemCount: 'العناصر المحددة: {{count}}', settings: 'الإعدادات', settingsSaved: 'تم حفظ الإعدادات.',
    sourceCleanupMode: 'معالجة الملفات المصدر', sourceCleanupKeep: 'الاحتفاظ بالملفات المصدر', sourceCleanupAfterOperation: 'حذف الكل بعد نجاح العملية', sourceCleanupAfterFile: 'الحذف بعد نجاح كل ملف', sourceCleanupAfterPart: 'الحذف بعد نجاح كل جزء', stagedContentLocation: 'موقع التخزين المؤقت', stagedContentLocationHint: 'مكان تخزين المحتوى عند تطبيق التغييرات دون اتصال بمحتوى مشفّر. اتركه فارغاً لاستخدام سطح المكتب تلقائياً.', stagedContentLocationAutoHint: 'تلقائي (سطح المكتب)',
    operationRunning: 'قيد التنفيذ', operationPreparing: 'جارٍ التحضير', operationPhaseEncrypting: 'التشفير', operationPhaseDecrypting: 'فك التشفير', operationPhaseVerifying: 'التحقق', operationPhaseFinalizing: 'الإنهاء', theme: 'السمة', themeDark: 'داكن', themeLight: 'فاتح', themeSystem: 'النظام', save: 'حفظ', unavailable: 'غير متاح', viewOpenSourceLicenses: 'عرض إشعارات الجهات الخارجية',
} as const;

export default ar;
