// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ClearRecentPaths() {
  return window['go']['main']['App']['ClearRecentPaths']();
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function ImportProject(arg1) {
  return window['go']['main']['App']['ImportProject'](arg1);
}

export function InspectProject(arg1) {
  return window['go']['main']['App']['InspectProject'](arg1);
}

export function ListLocalProjects() {
  return window['go']['main']['App']['ListLocalProjects']();
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function VerifyProject(arg1) {
  return window['go']['main']['App']['VerifyProject'](arg1);
}
