// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function ClearRecentPaths():Promise<main.Settings>;

export function InspectProject(arg1:main.InspectProjectRequest):Promise<main.InspectProjectResult>;

export function ListLocalProjects():Promise<Array<main.LocalProjectSummary>>;

export function ReadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;
