// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function ApplyProjectChanges(arg1:main.ApplyProjectChangesRequest):Promise<main.ApplyProjectChangesResult>;

export function CreateProject(arg1:main.CreateProjectRequest):Promise<main.CreateProjectResult>;

export function CreateShare(arg1:main.CreateShareRequest):Promise<main.CreateShareResult>;

export function DecryptProject(arg1:main.DecryptProjectRequest):Promise<main.DecryptProjectResult>;

export function DecryptShare(arg1:main.DecryptShareRequest):Promise<main.DecryptShareResult>;

export function DeleteProject(arg1:main.DeleteProjectRequest):Promise<main.DeleteProjectResult>;

export function ExportProject(arg1:main.ExportProjectRequest):Promise<main.ExportProjectResult>;

export function ImportProject(arg1:main.ImportProjectRequest):Promise<main.ImportProjectResult>;

export function InspectProject(arg1:main.InspectProjectRequest):Promise<main.InspectProjectResult>;

export function ListLocalProjects():Promise<Array<main.LocalProjectSummary>>;

export function LoadShare(arg1:main.LoadShareRequest):Promise<main.ShareSummary>;

export function OpenProjectBrowser(arg1:main.OpenProjectBrowserRequest):Promise<main.ProjectBrowserState>;

export function ReadSettings():Promise<main.Settings>;

export function SaveLocalProjectName(arg1:main.SaveLocalProjectNameRequest):Promise<main.SaveLocalProjectNameResult>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;

export function SelectPath(arg1:main.SelectPathRequest):Promise<string>;

export function SetLongRunningOperationActive(arg1:boolean):Promise<void>;

export function SetManualContentGuideCloseGuardActive(arg1:boolean,arg2:string):Promise<void>;

export function VerifyProject(arg1:main.VerifyProjectRequest):Promise<main.VerifyProjectResult>;

export function VerifyShare(arg1:main.VerifyShareRequest):Promise<main.VerifyProjectResult>;
