// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AppInfo() {
  return window['go']['main']['App']['AppInfo']();
}

export function ApplyProjectChanges(arg1) {
  return window['go']['main']['App']['ApplyProjectChanges'](arg1);
}

export function ChangeProjectPassword(arg1) {
  return window['go']['main']['App']['ChangeProjectPassword'](arg1);
}

export function ChangeSharePassword(arg1) {
  return window['go']['main']['App']['ChangeSharePassword'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateShare(arg1) {
  return window['go']['main']['App']['CreateShare'](arg1);
}

export function DecryptProject(arg1) {
  return window['go']['main']['App']['DecryptProject'](arg1);
}

export function DecryptShare(arg1) {
  return window['go']['main']['App']['DecryptShare'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function ExportProject(arg1) {
  return window['go']['main']['App']['ExportProject'](arg1);
}

export function ImportProject(arg1) {
  return window['go']['main']['App']['ImportProject'](arg1);
}

export function InspectProject(arg1) {
  return window['go']['main']['App']['InspectProject'](arg1);
}

export function ListLocalProjects() {
  return window['go']['main']['App']['ListLocalProjects']();
}

export function ListProjectBackups(arg1) {
  return window['go']['main']['App']['ListProjectBackups'](arg1);
}

export function LoadShare(arg1) {
  return window['go']['main']['App']['LoadShare'](arg1);
}

export function OpenProjectBrowser(arg1) {
  return window['go']['main']['App']['OpenProjectBrowser'](arg1);
}

export function ReadSettings() {
  return window['go']['main']['App']['ReadSettings']();
}

export function RestoreProjectBackup(arg1) {
  return window['go']['main']['App']['RestoreProjectBackup'](arg1);
}

export function SaveLocalProjectName(arg1) {
  return window['go']['main']['App']['SaveLocalProjectName'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SelectPath(arg1) {
  return window['go']['main']['App']['SelectPath'](arg1);
}

export function SetManualContentGuideCloseGuardActive(arg1, arg2) {
  return window['go']['main']['App']['SetManualContentGuideCloseGuardActive'](arg1, arg2);
}

export function SetUILanguage(arg1) {
  return window['go']['main']['App']['SetUILanguage'](arg1);
}

export function VerifyProject(arg1) {
  return window['go']['main']['App']['VerifyProject'](arg1);
}

export function VerifyShare(arg1) {
  return window['go']['main']['App']['VerifyShare'](arg1);
}
