// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AppInfo():Promise<main.AppInfo>;

export function ClearRecentPaths():Promise<main.Settings>;

export function DeleteProject(arg1:main.DeleteProjectRequest):Promise<main.DeleteProjectResult>;

export function ExportProject(arg1:main.ExportProjectRequest):Promise<main.ExportProjectResult>;

export function ImportProject(arg1:main.ImportProjectRequest):Promise<main.ImportProjectResult>;

export function InspectProject(arg1:main.InspectProjectRequest):Promise<main.InspectProjectResult>;

export function ListLocalProjects():Promise<Array<main.LocalProjectSummary>>;

export function ReadSettings():Promise<main.Settings>;

export function SaveSettings(arg1:main.Settings):Promise<main.Settings>;
